export const getDataSuccess = 'get data successfully';
export const getDataFailed = 'get data failed';
export const updateDataSuccess = 'update data successfully';
export const updateDataFailed = 'update data failed';
export const updatePasswordSuccess = 'update password successfully';
export const updatePasswordFailed = 'update password failed';
export const deleteDataSuccess = 'delete data successfully';
export const deleteDataFailed = 'delete data failed';
export const registerSuccess = 'register successfully';
export const registerFailed = 'register failed';
export const emailIsUnique = 'email already in use';
export const authLoginSuccess = 'login successfully'
export const authLoginFailed = 'login failed'
export const accountNotRegister = 'account not register'
export const emailPassworWrong = 'email or password is wrong'
export const unAuthorized = 'Unauthorized'
export const userUnauthorized = 'user Unauthorized'
export const storeUnauthorized = 'store Unauthorized'
export const dataNotFound = 'data not found'
export const createFileSuccess = 'create file successfully'
export const createFileFailed = 'create file failed'
export const fileMustImage = 'file must be image'

