export const getDataSuccess = 'get data successfully';
export const getDataFailed = 'get data failed';
export const registerSuccess = 'register successfully';
export const registerFailed = 'register failed';
export const emailIsUnique = 'email already in use';
export const authLoginSuccess = 'login successfully'
export const authLoginFailed = 'login failed'
export const accountNotRegister = 'account not register'
export const emailPassworWrong = 'email or password is wrong'
export const unAuthorized = 'Unauthorized'
export const userUnauthorized = 'user Unauthorized'
export const storeUnauthorized = 'store Unauthorized'
